name: random_post
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.15.1
  google_fonts: ^5.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

# flutter_native_splash:
#   color: "#42a5f5"
#   image: assets/image/logo.png
#   color_dark: "#042a49"
#   background_image_dark: assets/image/logo.png

#   android_12:
#     image: assets/image/logo.png
#     icon_background_color: "#111111"
#     image_dark: assets/image/logo.png
#     icon_background_color_dark: "#eeeeee"


flutter: 
  uses-material-design: true
  assets:
    - assets/image/

