// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDTANI-JhDlBCslge1928q9QdMnM0fOg0',
    appId: '1:549198001584:web:bead49bbea79fe0e759275',
    messagingSenderId: '549198001584',
    projectId: 'postrandom-a1772',
    authDomain: 'postrandom-a1772.firebaseapp.com',
    storageBucket: 'postrandom-a1772.appspot.com',
    measurementId: 'G-9CYMR03203',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD3Hga0THpP9HHR2b3v3BugojjF4AGD-k',
    appId: '1:549198001584:android:a39374a32b76c4c5759275',
    messagingSenderId: '549198001584',
    projectId: 'postrandom-a1772',
    storageBucket: 'postrandom-a1772.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Js23Oj_xE6vg_M9VBMBbA4xjVAuGdj0',
    appId: '1:549198001584:ios:1bd33d26c715b1a7759275',
    messagingSenderId: '549198001584',
    projectId: 'postrandom-a1772',
    storageBucket: 'postrandom-a1772.appspot.com',
    iosClientId: '549198001584-h2nodr1rdrqs85kr48g6o7nkkrvoegui.apps.googleusercontent.com',
    iosBundleId: 'com.funcode.randomPost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Js23Oj_xE6vg_M9VBMBbA4xjVAuGdj0',
    appId: '1:549198001584:ios:1d1144656e4e1511759275',
    messagingSenderId: '549198001584',
    projectId: 'postrandom-a1772',
    storageBucket: 'postrandom-a1772.appspot.com',
    iosClientId: '549198001584-kdsnem26hj2qoqodv7icc20pvg8a1u9t.apps.googleusercontent.com',
    iosBundleId: 'com.funcode.randomPost.RunnerTests',
  );
}
